# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.gprMCMC <- function(y, X, nburn, nsample, b, B, e, E, shape, scale, minloops, maxloops, ntune, target_rate, rate_tol, prop_scale, weight, verbose) {
    .Call(`_gpr_gprMCMC`, y, X, nburn, nsample, b, B, e, E, shape, scale, minloops, maxloops, ntune, target_rate, rate_tol, prop_scale, weight, verbose)
}

.gprMCMCZ <- function(y, X, nburn, nsample, e, E, shape, scale, minloops, maxloops, ntune, target_rate, rate_tol, prop_scale, weight, verbose) {
    .Call(`_gpr_gprMCMCZ`, y, X, nburn, nsample, e, E, shape, scale, minloops, maxloops, ntune, target_rate, rate_tol, prop_scale, weight, verbose)
}

.gpr_predict <- function(P, y, X, Z) {
    .Call(`_gpr_gpr_predict`, P, y, X, Z)
}

.gpr_predictZ <- function(P, y, X, Z) {
    .Call(`_gpr_gpr_predictZ`, P, y, X, Z)
}

